server:
  port: 7777
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-cbbmajng.sql.tencentcdb.com:24095/sg_blog
    username: root
    password: Banxing4116
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
logging:
  level:
    root: info
  config: classpath:slf4j.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
