# 服务器配置
server:
  port: 7777  # 指定服务器监听的端口号
  address: 0.0.0.0  # 监听的地址

# 日志配置
logging:
  level:
    root: info  # 根日志级别
  config: classpath:slf4j.xml  # 日志配置文件路径

# SpringDoc配置（用于Swagger文档生成）
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI的访问路径
